### ISSUE TITLE
Mendix 9 Compatibility

### ISSUE THREAD

**Issue by PLITSGE** [tieniber/PrintScreen#7]
Hi
Thanks for creating this nice widget!
The Version 1.0 of the PrintScreen Widget ist not compatible with Mendix 9.
Any Update planned?
Thanks Stephan

**Comment by RCatersels** [comment]
See forum post here: https://forum.mendixcloud.com/link/questions/106778 
Fix is super simple to get it working again in Mx9. Do note that this widget can no longer be downloaded from the marketplace. 
Regards,
Ronald

**Comment by PLITSGE** [comment]
Hi Ronald!

Great to hear and thanks a lot for the info!

Have a nice day!
Stephan

**Comment by tieniber** [comment]
I actually released a new version to the marketplace yesterday! So you can download v1.0.1 from the marketplace now.
